from tkinter import *
from tkinter import ttk 
window = Tk()
progressbar = ttk.Progressbar(window,orient=HORIZONTAL,length=200)
progressbar.pack()
progressbar.config(mode='indeterminate')
progressbar.start()
progressbar.stop()
progressbar.config(mode='determinate', maximum=12.0,value=1.2)
value = DoubleVar()
progressbar.config(variable=value)
scale = ttk.Scale(window,orient=HORIZONTAL,variable=value,from_ = 0,to = 12)
scale.set(3.4)
scale.pack()
window.mainloop()